### ISSUE TITLE
fails to find git url for many (all?) monolingual packages

### ISSUE THREAD

**Issue by sushain97** [unhammer/apertium-get#9]
```
$ ./apertium-get cat
WARNING: Couldn't find git url of cat
```

FYI, if http://apertium.projectjj.com/stats-service/packages makes things easier, might be worth using.

:(

**Comment by sushain97** [comment]
cc @unhammer

**Comment by sushain97** [comment]
Ah, I think it works only with `apertium-cat` now. So, this is just a regression, not a bug?

Also, it seems that the output of `./apertium-get -m` contains pairs from `incubator`?

```
# Language modules in incubator:
fin-hun
msa
spa-deu
sw-rn
zul
gld
gle-eng
mlt-spa
rus-eng
lt-lv
ibo
wal
eng-ita
udm-kpv
swe-eng
vro-est
ina-spa
dar
```

**Comment by sushain97** [comment]
Similarly, `./apertium-get -l` also contains modules instead of only pairs.

**Comment by sushain97** [comment]
Awesome! Everything seems to work now and beta.apertium.org is updating as I type. Thanks for your quick response.

**Comment by unhammer** [comment]
no problem :)
